### PR TITLE
Comfocool

### PR DESCRIPTION
**Pull request by michaelarnauts**
To test:

Place a `test.py` file in the root and run it with `python3 ./test.py`:
```py
import logging

_LOGGER = logging.getLogger(__name__)

logging.basicConfig(level=logging.DEBUG)
import asyncio

from aiocomfoconnect import ComfoConnect


async def main(local_uuid, host, uuid):
    """ Basic example."""

    # Connect to the Bridge
    comfoconnect = ComfoConnect(host, uuid)
    await comfoconnect.connect(local_uuid)

    # Loop for 5 seconds
    for i in range(5):
        mode = await comfoconnect.get_comfocool_mode()
        print("Current Comfocool Mode: {}".format(mode))
        await asyncio.sleep(1)

    # Enable
    print('Enabling...')
    await comfoconnect.set_comfocool_mode(True)
    await asyncio.sleep(5)

    # Disable
    print('Disabling...')
    await comfoconnect.set_comfocool_mode(False)
    await asyncio.sleep(5)

    # Disconnect from the bridge
    await comfoconnect.disconnect()


if __name__ == "__main__":
    asyncio.run(main(local_uuid='00000000000000000000000000000001',
                     host='192.168.1.213',
                     uuid='0000000000251010800170b3d54264b4'))  # Replace with your bridge's IP and UUID
```

Replace local_uuid/host/uuid to match your own.

### CODE REVIEW

**Comment by gertst** [comment]
Hi Michael,

I tried the above script, but I'm afraid I don't know what to fill in for local_uuid and uuid ...

I should probably fill in some of these?
image

My guess is to use the first and the last one, but I keep on getting this error, even when I reverse the uuids:

````
python.exe test.py
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:aiocomfoconnect.bridge:Disconnecting from bridge 192.168.68.163
DEBUG:aiocomfoconnect.bridge:Disconnected from bridge 192.168.68.163
DEBUG:aiocomfoconnect.bridge:Connecting to bridge 192.168.68.163
DEBUG:aiocomfoconnect.bridge:Connected to bridge 192.168.68.163
DEBUG:aiocomfoconnect.bridge:StartSessionRequest
DEBUG:aiocomfoconnect.bridge:Adding listener for event 1
DEBUG:aiocomfoconnect.bridge:TX 00000000000000000000000000000001 -> 00000000000000000000000000000005: 08032001 0801
type: StartSessionRequestType
reference: 1

takeover: true

WARNING:aiocomfoconnect.bridge:Timeout while waiting for response from bridge
Traceback (most recent call last):
  File "C:\Users\gerts\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gerts\OneDrive\Documents\gitProjects\aiocomfoconnect\aiocomfoconnect\bridge.py", line 168, in _send
    return await asyncio.wait_for(fut, TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerts\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gerts\OneDrive\Documents\gitProjects\aiocomfoconnect\test.py", line 39, in <module>
    asyncio.run(main(local_uuid='00000000000000000000000000000001',
  File "C:\Users\gerts\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\gerts\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerts\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\gerts\OneDrive\Documents\gitProjects\aiocomfoconnect\test.py", line 16, in main
    await comfoconnect.connect(local_uuid)
  File "C:\Users\gerts\OneDrive\Documents\gitProjects\aiocomfoconnect\aiocomfoconnect\comfoconnect.py", line 74, in connect
    await self.cmd_start_session(True)
  File "C:\Users\gerts\OneDrive\Documents\gitProjects\aiocomfoconnect\aiocomfoconnect\bridge.py", line 171, in _send
    raise AioComfoConnectTimeout from exc
aiocomfoconnect.exceptions.AioComfoConnectTimeout
````

My lack of knowledge of Python and the Zehnder protocol is not helping eighter :-/

**Comment by michaelarnauts** [comment]
Local uuid can be the 0000...1, since that's registered. As IP and UUID, you'll need to pick the IP of your bridge, and the UUID of the unit on your bridge. You can find this when doing a discover.

**Comment by gertst** [comment]
Good news:
I found the right uuids by increasing the debug level in the comfoconnect module and check the listed uuids there ;-)
And now I can run the script.

I did find some issues but was able to fix them:

- The status should be the other way around:
  Current Comfocool Mode: False --> should be True: for some reason on = -1 and off = 0.
- Turning it on or off is the other way around: so the if and else clause should be swapped in `set_comfocool_mode`.
- Turning it on does work (=command `await self.cmd_rmi_request(bytes([0x85, UNIT_SCHEDULE, SUBUNIT_05, 0x01]))` )
- Turning it off did NOT work, but I could solve the issue: the line ` await self.cmd_rmi_request(bytestring([0x84, UNIT_SCHEDULE, SUBUNIT_05, 0x06, 0x00, 0x00, 0x00, 0x00, timeout.to_bytes(4, "little", signed=True), 0x00]))` should be `await self.cmd_rmi_request(bytestring([0x84, UNIT_SCHEDULE, SUBUNIT_05, 0x01, 0x00, 0x00, 0x00, 0x00, timeout.to_bytes(4, "little", signed=True), 0x00]))` --> 0x06 should be 0x01

So I did some updates to your code and now all works as expected :-)
````
    async def get_comfocool_mode(self):
        """Get the current comfocool mode."""
        result = await self.cmd_rmi_request(bytes([0x83, UNIT_SCHEDULE, SUBUNIT_05, 0x01]))
        mode = result.message[0]
        print('result:', mode)
        return mode == 0 #changed the check here

    async def set_comfocool_mode(self, mode: bool, timeout=-1):
        """Set the comfocool mode (auto / off)."""
        #swapped the if/else here:
        if mode:
            await self.cmd_rmi_request(bytes([0x85, UNIT_SCHEDULE, SUBUNIT_05, 0x01]))
        else:
            await self.cmd_rmi_request(bytestring([0x84, UNIT_SCHEDULE, SUBUNIT_05, 0x01, 0x00, 0x00, 0x00, 0x00, timeout.to_bytes(4, "little", signed=True), 0x00]))

````

**Comment by gertst** [comment]
When you have a chance, could you give me an update on the estimated timeline for merging this PR?
I don't mean to rush you - Just let me know if there's anything I can do to help.

**Comment by michaelarnauts** [comment]
I'm sorry, I lost track of this PR. I still need to modify it with your remarks. Shouldn't take that much time, but I need to find the time to do this. Life is a bit busy at the moment, sorry.

**Comment by michaelarnauts** [comment]
I've modified the PR with your changes, but one this looks odd. You mention that the status is on = -1 and off = 0, but in your code, you return `mode == 0`, so when mode is 0, you will return true, indicating that the comfocool is on.

I have committed it to that it returns True when the mode == -1, but you might want to check this.

**Comment by gertst** [comment]
To simplify the code updates, I did the changes in a new Pull Request, because I was not able to update in here ...
Hope that's oke.

**Pull request merged**
